#!/bin/bash
#===============================================================================
# Janitor - A little bash script to make janitorial duties easier :)
# Copyright (C) 2024-2026 kvastlund
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# TODO: Make man page!
#======> CONSTANTS <============================================================

readonly HELP_STRING=$'
\e[1mUsage:\e[0m
    janitor
    janitor <operation>
    janitor <operation> [...]

\e[1mSetup operations:\e[0m

    \e[1m--install\e[0m
        Create a symlink to this script called \e[3mjanitor\e[0m in /usr/local/bin.

    \e[1m--uninstall\e[0m
        Remove a symlink to this script called \e[3mjanitor\e[0m from /usr/local/bin.

    \e[1m--patches\e[0m
        List available patches.

    \e[1m--patch\e[0m <patches>
        Apply specified patches.

    \e[1m--unpatch\e[0m <patches>
        Remove specified patches.

\e[1mMain operations:\e[0m

    \e[1m<no operation>, --greet\e[0m
        Display an informative greeting.

    \e[1m-h, --help\e[0m
        Display this help.

    \e[1m-u, --upgrade\e[0m <package(s)>
        Upgrade the system and optionally install packages.
        This will upgrade official and AUR packages, and run pacdiff and clean
        up afterwards.

    \e[1m-i, --installpkg\e[0m <package(s)>
        Install packages.

    \e[1m-r, --removepkg\e[0m <package(s)>
        Remove packages.

    \e[1m-c, --clean\e[0m
        Clean up after pacman and paru.

    \e[1m-x, --expel\e[0m <paths>
        Move files and directories to trash.

    \e[1m--sysinfo\e[0m
        Display system information.

    \e[1m--mpvwebcam\e[0m
        Display webcam output in mpv.

\e[1mDeprecated operations:\e[0m

    \e[1m--rewifi\e[0m
        Reload wifi driver module.
'

SCRIPTS_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")/scripts
readonly SCRIPTS_PATH

#======> FUNCTIONS <============================================================

_install() {
    sudo ln -s "$(realpath "${BASH_SOURCE[0]}")" /usr/local/bin
}

_uninstall() {
    sudo unlink /usr/local/bin/janitor
}

_opt_error() {
    echo -e "\e[91;1mError:\e[22m Invalid option $2-$1\e[0m"
    echo "Try 'janitor --help' for more information."
}

#======> GO! <==================================================================

if [ $# -eq 0 ]; then
    "$SCRIPTS_PATH"/greet
    exit
fi

while getopts ":hcui:r:x:-:" opt; do
    case $opt in
        h)  echo "$HELP_STRING"
            exit;;
        c)  "$SCRIPTS_PATH"/clean
            exit;;
        u)  systemd-inhibit "$SCRIPTS_PATH"/upgrade "${@:2}"
            exit;;
        i)  systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
            exit;;
        r)  "$SCRIPTS_PATH"/removepkg "${@:2}"
            exit;;
        x)  "$SCRIPTS_PATH"/expel "${@:2}"
            exit;;
        -)  case $OPTARG in
                help)       echo "$HELP_STRING"
                            exit;;
                clean)      "$SCRIPTS_PATH"/clean
                            exit;;
                upgrade)    systemd-inhibit "$SCRIPTS_PATH"/upgrade "${@:2}"
                            exit;;
                installpkg) systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
                            exit;;
                removepkg)  "$SCRIPTS_PATH"/removepkg "${@:2}"
                            exit;;
                expel)      "$SCRIPTS_PATH"/expel "${@:2}"
                            exit;;
                greet)      "$SCRIPTS_PATH"/greet
                            exit;;
                mpvwebcam)  "$SCRIPTS_PATH"/mpvwebcam
                            exit;;
                sysinfo)    "$SCRIPTS_PATH"/sysinfo
                            exit;;
                mirtime)    "$SCRIPTS_PATH"/mirtime "$2"
                            exit;;
                install)    _install
                            exit;;
                uninstall)  _uninstall
                            exit;;
                patches)    "$SCRIPTS_PATH"/patch list
                            exit;;
                patch)      "$SCRIPTS_PATH"/patch apply "${@:2}"
                            exit;;
                unpatch)    "$SCRIPTS_PATH"/patch remove "${@:2}"
                            exit;;
                rewifi)     "$SCRIPTS_PATH"/rewifi
                            exit;;
                *)          # Invalid option
                            _opt_error "$OPTARG" "-"
                            exit 1;;
            esac;;
        \?) # Invalid option
            _opt_error "$OPTARG"
            exit 1;;
    esac
done

#===============================================================================
