#!/bin/bash

SCRIPTS_PATH=$(dirname "$(realpath "$0")")/utility_scripts

_help() {
    echo
    echo -e "\e[1mMaintenance and utility scripts.\e[0m"
    echo
    echo -e "\e[1mSynopsis:\e[0m janitor <operation> [options] [target]"
    echo
    echo -e "\e[1mOperations:\e[0m"
    echo -e "    \e[1m<no operation>, --greet\e[0m"
    echo "        Display an informative greeting."
    echo
    echo -e "    \e[1m-u, --upgrade\e[0m"
    echo "        Update and upgrade the system."
    echo
    echo -e "    \e[1m-i, --installpkg\e[0m <package>"
    echo "        Install a package."
    echo
    echo -e "    \e[1m-r, --removepkg\e[0m <package>"
    echo "        Remove a package."
    echo
    echo -e "    \e[1m-c, --clean\e[0m"
    echo "        Clean up after pacman and paru."
    echo
    echo -e "    \e[1m-x, --expel\e[0m <path>"
    echo "        Move a file or directory to trash."
    echo
    echo -e "    \e[1m--mpvwebcam\e[0m"
    echo "        Display webcam output in mpv."
    echo
    echo -e "    \e[1m--rewifi\e[0m"
    echo "        Reload wifi driver module."
    echo
    echo -e "    \e[1m--sysinfo\e[0m"
    echo "        Display system information."
    echo
    echo -e "    \e[1m--mirlisttime\e[0m [options]"
    echo "        Display when the current mirrorlist was retrieved."
    echo
    echo -e "            \e[1m-n\e[0m      Display an empty line before and after the message if there"
    echo "                    is one."
    echo
    echo -e "    \e[1m--install\e[0m"
    echo -e "        Create a symlink to this script called \e[3mjanitor\e[0m in /usr/local/bin."
    echo
    echo -e "    \e[1m--uninstall\e[0m"
    echo -e "        Remove a symlink to this script called \e[3mjanitor\e[0m from /usr/local/bin."
    echo
    echo -e "    \e[1m--patches\e[0m"
    echo -e "        List available patches."
    echo
    echo -e "    \e[1m--patch\e[0m <patch>"
    echo -e "        Apply a patch."
    echo
    echo -e "    \e[1m--unpatch\e[0m <patch>"
    echo -e "        Remove a patch."
    echo
    echo -e "    \e[1m-h, --help\e[0m"
    echo "        Print this help."
    echo
}

_install() {
    sudo ln -s "$(realpath "$0")" /usr/local/bin
}

_uninstall() {
    sudo unlink /usr/local/bin/janitor
}

if [ $# -eq 0 ]; then
    "$SCRIPTS_PATH"/greet
    exit
fi

while getopts ":hcu:i:r:x:-:" opt; do
    case $opt in
        h)  _help
            exit;;
        c)  "$SCRIPTS_PATH"/clean
            exit;;
        u)  systemd-inhibit "$SCRIPTS_PATH"/upgrade
            exit;;
        i)  systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
            exit;;
        r)  "$SCRIPTS_PATH"/removepkg "${@:2}"
            exit;;
        x)  "$SCRIPTS_PATH"/expel "${@:2}"
            exit;;
        -)  case $OPTARG in
                help)           _help
                                exit;;
                clean)          "$SCRIPTS_PATH"/clean
                                exit;;
                upgrade)        systemd-inhibit "$SCRIPTS_PATH"/upgrade "${@:2}"
                                exit;;
                installpkg)     systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
                                exit;;
                removepkg)      "$SCRIPTS_PATH"/removepkg "${@:2}"
                                exit;;
                expel)          "$SCRIPTS_PATH"/expel "${@:2}"
                                exit;;
                greet)          "$SCRIPTS_PATH"/greet
                                exit;;
                mpvwebcam)      "$SCRIPTS_PATH"/mpvwebcam
                                exit;;
                sysinfo)        "$SCRIPTS_PATH"/sysinfo
                                exit;;
                mirlisttime)    "$SCRIPTS_PATH"/mirlisttime $2
                                exit;;
                install)        _install
                                exit;;
                uninstall)      _uninstall
                                exit;;
                patches)        "$SCRIPTS_PATH"/patch list
                                exit;;
                patch)          "$SCRIPTS_PATH"/patch apply "${@:2}"
                                exit;;
                unpatch)        "$SCRIPTS_PATH"/patch remove "${@:2}"
                                exit;;
                rewifi)         "$SCRIPTS_PATH"/rewifi
                                exit;;
                *)              # Invalid option
                                echo -e "\e[91;1mError:\e[22m Invalid option --$OPTARG\e[0m"
                                exit 1;;
            esac;;
        \?) # Invalid option
            echo -e "\e[91;1mError:\e[22m Invalid option -$OPTARG\e[0m"
            exit 1;;
    esac
done
