#!/bin/bash

#TODO: Make man page!
help_string=$'
\e[1mUsage:\e[0m
    janitor
    janitor <operation>
    janitor <operation> [...]

\e[1mSetup operations:\e[0m

    \e[1m--install\e[0m
        Create a symlink to this script called \e[3mjanitor\e[0m in /usr/local/bin.

    \e[1m--uninstall\e[0m
        Remove a symlink to this script called \e[3mjanitor\e[0m from /usr/local/bin.

    \e[1m--patches\e[0m
        List available patches.

    \e[1m--patch\e[0m <patches>
        Apply specified patches.

    \e[1m--unpatch\e[0m <patches>
        Remove specified patches.

\e[1mMain operations:\e[0m

    \e[1m<no operation>, --greet\e[0m
        Display an informative greeting.

    \e[1m-h, --help\e[0m
        Display this help.

    \e[1m-u, --upgrade\e[0m <package(s)>
        Upgrade the system and optionally install packages.
        This will upgrade official and AUR packages, and run pacdiff and clean
        up afterwards.

    \e[1m-i, --installpkg\e[0m <package(s)>
        Install packages.

    \e[1m-r, --removepkg\e[0m <package(s)>
        Remove packages.

    \e[1m-c, --clean\e[0m
        Clean up after pacman and paru.

    \e[1m-x, --expel\e[0m <paths>
        Move files and directories to trash.

    \e[1m--sysinfo\e[0m
        Display system information.

    \e[1m--mpvwebcam\e[0m
        Display webcam output in mpv.

    \e[1m--mirtime\e[0m [options]
        Display when the current mirrorlist was retrieved.

            \e[1m-n\e[0m      Display an empty line before and after the message, if there
                    is one.

\e[1mDeprecated operations:\e[0m

    \e[1m--rewifi\e[0m
        Reload wifi driver module.
'

scripts_path=$(dirname "$(realpath "$0")")/utility_scripts

_install() {
    sudo ln -s "$(realpath "$0")" /usr/local/bin
}

_uninstall() {
    sudo unlink /usr/local/bin/janitor
}

_opt_error() {
    echo -e "\e[91;1mError:\e[22m Invalid option $2-$1\e[0m"
    echo "Try 'janitor --help' for more information."
}

if [ $# -eq 0 ]; then
    "$scripts_path"/greet
    exit
fi

while getopts ":hcui:r:x:-:" opt; do
    case $opt in
        h)  echo "$help_string"
            exit;;
        c)  "$scripts_path"/clean
            exit;;
        u)  systemd-inhibit "$scripts_path"/upgrade "${@:2}"
            exit;;
        i)  systemd-inhibit "$scripts_path"/installpkg "${@:2}"
            exit;;
        r)  "$scripts_path"/removepkg "${@:2}"
            exit;;
        x)  "$scripts_path"/expel "${@:2}"
            exit;;
        -)  case $OPTARG in
                help)       echo "$help_string"
                            exit;;
                clean)      "$scripts_path"/clean
                            exit;;
                upgrade)    systemd-inhibit "$scripts_path"/upgrade "${@:2}"
                            exit;;
                installpkg) systemd-inhibit "$scripts_path"/installpkg "${@:2}"
                            exit;;
                removepkg)  "$scripts_path"/removepkg "${@:2}"
                            exit;;
                expel)      "$scripts_path"/expel "${@:2}"
                            exit;;
                greet)      "$scripts_path"/greet
                            exit;;
                mpvwebcam)  "$scripts_path"/mpvwebcam
                            exit;;
                sysinfo)    "$scripts_path"/sysinfo
                            exit;;
                mirtime)    "$scripts_path"/mirtime $2
                            exit;;
                install)    _install
                            exit;;
                uninstall)  _uninstall
                            exit;;
                patches)    "$scripts_path"/patch list
                            exit;;
                patch)      "$scripts_path"/patch apply "${@:2}"
                            exit;;
                unpatch)    "$scripts_path"/patch remove "${@:2}"
                            exit;;
                rewifi)     "$scripts_path"/rewifi
                            exit;;
                *)          # Invalid option
                            _opt_error $OPTARG "-"
                            exit 1;;
            esac;;
        \?) # Invalid option
            _opt_error $OPTARG
            exit 1;;
    esac
done
