#!/bin/bash

_help() {
    echo "Maintenance and utility scripts."
    echo
    echo "Syntax: memma [-g|h|v|V]"
    echo "options:"
    echo "g     Print the GPL license notification."
    echo "h     Print this Help."
    echo "v     Verbose mode."
    echo "V     Print software version and exit."
    echo
}

while getopts ":h" option; do
    case $option in
        h)  _help
            exit;;
        \?) # Invalid option
            echo "Error: Invalid option"
            exit;;
    esac
done
