#!/bin/bash

USER_SCRIPTS_PATH=$(dirname $(realpath $0))/user_scripts

_help() {
    echo -e "\e[1mMaintenance and utility scripts.\e[0m"
    echo
    echo -e "\e[1mSynopsis:\e[0m memma <operation> [target]"
    echo
    echo -e "\e[1mOperations:\e[0m"
    echo -e "    \e[1m<no operation>, --hi\e[0m"
    echo "        Display an informative greeting."
    echo
    echo -e "    \e[1m-u, --up\e[0m"
    echo "        Update and upgrade the system."
    echo
    echo -e "    \e[1m-i, --in\e[0m <package>"
    echo "        Install a package."
    echo
    echo -e "    \e[1m-o, --out\e[0m <package>"
    echo "        Remove a package."
    echo
    echo -e "    \e[1m-c, --clean\e[0m"
    echo "        Clean up after pacman and paru."
    echo
    echo -e "    \e[1m-r, --rm\e[0m <path>"
    echo "        Remove a file or directory somewhat safely."
    echo
    echo -e "    \e[1m--mpvwebcam\e[0m"
    echo "        Display webcam output in mpv."
    echo
    echo -e "    \e[1m--rewifi\e[0m"
    echo "        Reload wifi driver module."
    echo
    echo -e "    \e[1m--install\e[0m"
    echo -e "        Create a symlink to this script called \e[3mmemma\e[0m in /usr/local/bin."
    echo
    echo -e "    \e[1m--uninstall\e[0m"
    echo -e "        Remove a symlink to this script called \e[3mmemma\e[0m from /usr/local/bin."
    echo
    echo -e "    \e[1m-h, --help\e[0m"
    echo "        Print this help."
    echo
}
_install() {
    sudo ln -s $(realpath $0) /usr/local/bin
}
_uninstall() {
    sudo unlink /usr/local/bin/memma
}

if [ $# -eq 0 ]; then
    $USER_SCRIPTS_PATH/hi
    exit
fi

while getopts ":hcui:o:r:-:" opt; do
    case $opt in
        h)  _help
            exit;;
        c)  $USER_SCRIPTS_PATH/clean
            exit;;
        u)  $USER_SCRIPTS_PATH/up
            exit;;
        i)  $USER_SCRIPTS_PATH/in ${@:2}
            exit;;
        o)  $USER_SCRIPTS_PATH/out ${@:2}
            exit;;
        r)  $USER_SCRIPTS_PATH/rm ${@:2}
            exit;;
        -)  case $OPTARG in
                help)       _help
                            exit;;
                clean)      $USER_SCRIPTS_PATH/clean
                            exit;;
                up)         $USER_SCRIPTS_PATH/up
                            exit;;
                in)         $USER_SCRIPTS_PATH/in ${@:2}
                            exit;;
                out)        $USER_SCRIPTS_PATH/out ${@:2}
                            exit;;
                rm)         $USER_SCRIPTS_PATH/rm ${@:2}
                            exit;;
                hi)         $USER_SCRIPTS_PATH/hi
                            exit;;
                mpvwebcam)  $USER_SCRIPTS_PATH/mpvwebcam
                            exit;;
                install)    _install
                            exit;;
                uninstall)  _uninstall
                            exit;;
                rewifi)     $USER_SCRIPTS_PATH/rewifi
                            exit;;
                *)          # Invalid option
                            echo "Error: Invalid option --$OPTARG"
                            exit 1;;
            esac;;
        \?) # Invalid option
            echo "Error: Invalid option -$OPTARG"
            exit 1;;
    esac
done
