#!/bin/bash

_help() {
    echo -e "\e[1mMaintenance and utility scripts.\e[0m"
    echo
    echo -e "\e[1mSynopsis:\e[0m memma <operation> [target]"
    echo
    echo -e "\e[1mOperations:\e[0m"
    echo -e "    \e[1m--hi\e[0m"
    echo "        Display an informative greeting."
    echo
    echo -e "    \e[1m-u, --up\e[0m"
    echo "        Update and upgrade the system."
    echo
    echo -e "    \e[1m-i, --in\e[0m <package>"
    echo "        Install a package."
    echo
    echo -e "    \e[1m-o, --out\e[0m <package>"
    echo "        Remove a package."
    echo
    echo -e "    \e[1m-c, --clean\e[0m"
    echo "        Clean up after pacman and paru."
    echo
    echo -e "    \e[1m-r, --rm\e[0m <path>"
    echo "        Remove a file or directory somewhat safely."
    echo
    echo -e "    \e[1m--mpvwebcam\e[0m"
    echo "        Display webcam output in mpv."
    echo
    echo -e "    \e[1m--rewifi\e[0m"
    echo "        Reload wifi driver module."
    echo
    echo -e "    \e[1m-h, --help\e[0m"
    echo "        Print this help."
    echo
}

while getopts ":hcui:o:r:-:" opt; do
    case $opt in
        h)  _help
            exit;;
        c)  ./user_scripts/clean
            exit;;
        u)  ./user_scripts/up
            exit;;
        i)  ./user_scripts/in ${@:2}
            exit;;
        o)  ./user_scripts/out ${@:2}
            exit;;
        r)  ./user_scripts/rm ${@:2}
            exit;;
        -)  case $OPTARG in
                help)       _help
                            exit;;
                clean)      ./user_scripts/clean
                            exit;;
                up)         ./user_scripts/up
                            exit;;
                in)         ./user_scripts/in ${@:2}
                            exit;;
                out)        ./user_scripts/out ${@:2}
                            exit;;
                rm)         ./user_scripts/rm ${@:2}
                            exit;;
                hi)         ./user_scripts/hi
                            exit;;
                mpvwebcam)  ./user_scripts/mpvwebcam
                            exit;;
                rewifi)     ./user_scripts/rewifi
                            exit;;
                *)          # Invalid option
                            echo "Error: Invalid option --$OPTARG"
                            exit 1;;
            esac;;
        \?) # Invalid option
            echo "Error: Invalid option -$OPTARG"
            exit 1;;
    esac
done
