#!/bin/bash
#-------------------------------------------------------------------------------
# A little bash script to make management of a desktop file for kioclient,
# which shouldn't be needed if the bug was fixed properly, easier :)
# Copyright (C) 2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

PATCH_NAME=org.kde..desktop
PATCH_SOURCE=$(dirname "$(realpath "$0")")/$PATCH_NAME
PATCH_TARGET=/usr/share/applications

if [[ $1 == "apply" ]]; then
    sudo ln -s "$PATCH_SOURCE" $PATCH_TARGET
elif [[ $1 == "remove" ]]; then
    sudo unlink $PATCH_TARGET/$PATCH_NAME
else
    echo -e "\e[91;1mError:\e[22m Invalid operation $1\e[0m"
    exit 1
fi

#-------------------------------------------------------------------------------
