#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make removing stuff safely easier :)
#-------------------------------------------------------------------------------

trap 'echo -e "\e[0m"; exit' INT

#-------------------------------------------------------------------------------

for path in "${@:1}"; do
    if [ -w "$path" ]; then
        nosudos+=("$path")
    else
        yessudos+=("$path")
    fi
done

if [ ${#nosudos[@]} -ne 0 ]; then
    kioclient move "${nosudos[@]}" trash:/
fi

if [ ${#yessudos[@]} -ne 0 ]; then
    kioclient move "${yessudos[@]}" trash:/
fi

#-------------------------------------------------------------------------------
