#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make removing stuff safely easier :)
#-------------------------------------------------------------------------------

#for path in ${@:1}; do
#    if [ -e $path ]
#done


if [ -e "$1" ]; then
    kioclient move "${@:1}" trash:/
    
    [ -e "$1" ] && echo -e "\n\e[35mEnter password to remove permanently...\e[0m\n"
    
    if [ -f "$1" ]; then
        sudo -k rm "${@:1}"
    elif [ -d "$1" ]; then
        sudo -k rm -r "${@:1}"
    fi
else
    echo "idk wat u mean"
fi

#-------------------------------------------------------------------------------
