#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make viewing information about the system easier :)
#-------------------------------------------------------------------------------

echo

fastfetch

paru -Ps

#echo -e "\n\e[35m::\e[1;4mSince $(awk -F "[[ ]" 'NR==1 {print $2;}' /var/log/pacman.log)\e[0;35m::\e[0m\n"
echo -e "\n::\e[1;4mSince $(stat -c %w / | awk '{sub(/\.0{9}/, ""); print}')\e[0;35m::\e[0m\n"


#-------------------------------------------------------------------------------
