#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make updating and upgrading the system easier :)
#-------------------------------------------------------------------------------

trap "echo; exit" INT

#------->NEWS!<-----------------------------------------------------------------

echo -e "\e[35m"
paru -Pw
echo -e "\e[0m"

#------->update official and AUR<-----------------------------------------------

_upgrade() {
    paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter
}

if [ $# -gt 0 ]; then
    package=$(paru -Ss --interactive --bottomup $1)

    if [[ $package != "" ]]; then
        echo -ne "\e[1m"
        read -p "Install $package as a dependency? [y/N] " -n 1 -r
        echo -ne "\e[0m"

        [[ $REPLY != "" ]] && echo

        if [[ $REPLY =~ ^[Yy]$ ]]; then
            paru -Syu --asdeps --sudoloop --upgrademenu --bottomup --cleanafter $package
        else
            paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter $package
        fi
    else
        _upgrade
    fi
else
    _upgrade
fi

sudo -E pacdiff

echo
$(dirname $0)/clean

#------->Goodbye<---------------------------------------------------------------

echo -e "\n\e[1;35mThank you for upgrading me! See you soon i hope :)\e[0m\n"

#-------------------------------------------------------------------------------
