#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make updating and upgrading the system easier :)
#-------------------------------------------------------------------------------

trap 'echo -e "\e[0m"; exit' INT

#------->NEWS!<-----------------------------------------------------------------

duration="10s"

echo -e "\e[35m"
timeout $duration paru -Pw
if [ $? -eq 124 ]; then echo "'paru -Pw' timed out after $duration."; fi
echo -e "\e[0m"

#------->update official and AUR<-----------------------------------------------

if [ $# -gt 0 ]; then
    package=$(paru -Ss --interactive --bottomup "$1" | tee /dev/stderr | sed -n \$p | rev | cut -d ' ' -f 1 | rev)

    if [[ ($package != "") && ($package != "do") ]]; then
        echo
        "$(dirname "$0")"/mirlisttime
        echo

        while true; do
            echo -ne "\e[1m"
            read -p "Install $package as a dependency? [y/N] " -n 1 -r
            echo -ne "\e[0m"
            [[ $REPLY == "" ]] && break
            echo
            [[ ($REPLY =~ ^[Yy]$) || ($REPLY =~ ^[Nn]$) ]] && break
        done

        if [[ $REPLY =~ ^[Yy]$ ]]; then
            paru -Syu --asdeps --sudoloop --upgrademenu --bottomup --cleanafter "$package"
        else
            paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter "$package"
        fi
    else
        paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter
    fi
else
    paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter
fi

sudo -E pacdiff

echo
"$(dirname "$0")"/clean

#------->Goodbye<---------------------------------------------------------------

echo -e "\n\e[1;35mThank you for upgrading me! See you soon i hope :)\e[0m\n"

#-------------------------------------------------------------------------------
