#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make updating and upgrading the system easier :)
#-------------------------------------------------------------------------------

trap 'echo -e "\e[0m"; exit' INT

#------->NEWS!<-----------------------------------------------------------------

duration="10s"

echo -e "\e[35m"
timeout $duration paru -Pw
if [ $? -eq 124 ]; then echo "'paru -Pw' timed out after $duration."; fi
echo -e "\e[0m"

#------->update official and AUR<-----------------------------------------------

# TODO: Put the choosing in a separate script
# Choose packages
for query in "${@:1}"; do
    queryoutput=$(paru -Ss --interactive --bottomup --color always "$query" | tee /dev/stderr | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")

    pkgsstring=$(echo "${queryoutput##*:}" | xargs)

    if [[ ($pkgsstring != "") && ($pkgsstring != "there is nothing to do") ]]; then
        packages+=("$pkgsstring")
    fi
done
echo

# Choose dependencies
for pkg in ${packages[@]}; do
    while true; do
        echo -ne "\e[1m"
        read -p "Install $pkg as a dependency? [y/N] " -n 1 -r
        echo -ne "\e[0m"

        [[ $REPLY == "" ]] && break
        echo
        [[ ($REPLY =~ ^[Yy]$) || ($REPLY =~ ^[Nn]$) ]] && break
    done

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        dependencies+=("$(echo $pkg | cut -d '/' -f 2)")
    fi
done

"$(dirname "$0")"/mirtime -n

# Download and install
paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter ${packages[@]}

# Set dependencies
[ ${#dependencies[@]} -ne 0 ] && paru -D --asdeps ${dependencies[@]}

# Sort out the rest
sudo -E pacdiff
echo
"$(dirname "$0")"/clean

#------->Goodbye<---------------------------------------------------------------

echo -e "\n\e[1;35mThank you for upgrading me! See you soon i hope :)\e[0m\n"
exit 0

#-------------------------------------------------------------------------------
