#!/bin/bash
#===============================================================================
# A little bash script to make testing the webcam easier :)
# Copyright (C) 2024-2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#===============================================================================

mpv av://v4l2:/dev/video0 \
    --profile=low-latency \
    --untimed \
    --input-ipc-server=/tmp/mpvsocket \
    --script-opts=stats-duration=3600 \
    --wid=-1 \
    </dev/null &>/dev/null & disown

sleep 1

echo 'script-binding stats/display-stats' | socat - /tmp/mpvsocket

#===============================================================================
