#!/bin/bash

#-------------------------------------------------------------------------------
# A little bash script to make cleaning up after pacman and paru easier :)
#-------------------------------------------------------------------------------

trap 'echo -e "\e[0m"; exit' INT

#-------------------------------------------------------------------------------

echo -e "\e[1mLooking for poor little orphans to throw out on the street...\e[0m"
paru -c
echo

echo -e "\e[1mTidying up...\e[0m"
paru -Scd
echo

#-------------------------------------------------------------------------------
