#!/bin/bash
#-------------------------------------------------------------------------------
# A little bash script to make cleaning up after pacman and paru easier :)
# Copyright (C) 2025-2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

trap 'echo -e "\e[0m"; exit' INT

#-------------------------------------------------------------------------------

echo -e "\e[1mLooking for poor little orphans to throw out on the street...\e[0m"
paru -c
echo

echo -e "\e[1mTidying up...\e[0m"
paru -Scd
echo

#-------------------------------------------------------------------------------
