#!/bin/bash
#===============================================================================
# A little bash script to make removing stuff safely easier :)
# Copyright (C) 2024-2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#===============================================================================

trap 'echo -e "\e[0m"; exit' INT

#===============================================================================

for path in "${@:1}"; do
    if [ -w "$path" ]; then
        noprivs+=("$path")
    else
        yesprivs+=("$path")
    fi
done

if [ ${#noprivs[@]} -ne 0 ]; then
    kioclient move "${noprivs[@]}" trash:/
fi

if [ ${#yesprivs[@]} -ne 0 ]; then
    run0 --setenv=QT_QPA_PLATFORM=offscreen kioclient move "${yesprivs[@]}" trash:/
fi

#===============================================================================
