#!/bin/bash
#===============================================================================
# A little bash script to make installing stuff easier :)
# Copyright (C) 2024-2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#===============================================================================

trap 'echo -e "\e[0m"; exit' INT

#======> LIBRARIES <============================================================

. $(dirname "$(realpath "${BASH_SOURCE[0]}")")/utils.sh

#======> DO THE THING! <========================================================

# Choose packages and dependencies
util_setup_pkgs ${@:1}

# Display mirrorlist retrieved time
util_mirtime pad

# Download and install
if [ ${#util_packages[@]} -ne 0 ]; then
    # shellcheck disable=SC2068
    paru -S --sudoloop --upgrademenu --bottomup --cleanafter ${util_packages[@]}
fi

# Set dependencies
util_set_deps

exit 0

#===============================================================================
