#!/bin/bash
#-------------------------------------------------------------------------------
# A little bash script to make installing stuff easier :)
# Copyright (C) 2024-2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

trap 'echo -e "\e[0m"; exit' INT

#------> CONSTANTS <------------------------------------------------------------

SCRIPTS_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
readonly SCRIPTS_PATH

#------> DO THE THING! <--------------------------------------------------------

# TODO: Put the choosing in a separate script
# Choose packages
for query in "${@:1}"; do
    queryoutput=$(paru -Ss --interactive --bottomup --color always "$query" | tee /dev/stderr | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")

    pkgsstring=$(echo "${queryoutput##*:}" | xargs)

    if [[ ($pkgsstring != "") && ($pkgsstring != "there is nothing to do") ]]; then
        packages+=("$pkgsstring")
    fi
done
echo

# Choose dependencies
# shellcheck disable=SC2068
for pkg in ${packages[@]}; do
    while true; do
        echo -ne "\e[1m"
        read -p "Install $pkg as a dependency? [y/N] " -n 1 -r
        echo -ne "\e[0m"

        [[ $REPLY == "" ]] && break
        echo
        [[ ($REPLY =~ ^[Yy]$) || ($REPLY =~ ^[Nn]$) ]] && break
    done

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        dependencies+=("$(echo "$pkg" | cut -d '/' -f 2)")
    fi
done

"$SCRIPTS_PATH"/mirtime -n

# Download and install
if [ ${#packages[@]} -ne 0 ]; then
    # shellcheck disable=SC2068
    paru -S --sudoloop --upgrademenu --bottomup --cleanafter ${packages[@]}
fi

# Set dependencies
# shellcheck disable=SC2068
[ ${#dependencies[@]} -ne 0 ] && paru -D --asdeps ${dependencies[@]}

exit 0

#-------------------------------------------------------------------------------
