#!/bin/bash
#===============================================================================
# A little bash script to make keeping track of lines easier :)
# Copyright (C) 2026 kvastlund.
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#===============================================================================

trap 'echo -e "\e[0m"; exit' INT

#======> CONSTANTS <============================================================

readonly separator=$'\033[30;42m \033[0m '

#===============================================================================

input="$(cat)"

width=$(($(echo "$input" | wc -l | wc -m) - 1))

echo "$input" | nl -ba -fa -ha -s"$separator" -w"$width"

#===============================================================================
