#!/bin/bash
#-------------------------------------------------------------------------------
# A little bash script to make viewing when the mirrorlist was retrieved by
# reflector easier :)
# Copyright (C) 2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

retrieved_time=$(pacman -v 2> /dev/null | grep 'Conf File' | cut -d ' ' -f 4 | xargs cat | grep '\[core\]' -A 1 | grep 'Include' | cut -d ' ' -f 3 | xargs cat | grep 'Retrieved' | cut -d ' ' -f 4,5,6)

if [[ $retrieved_time != "" ]]; then
    [[ $1 == "-n" ]] && echo
    echo "The current mirrorlist was retrieved at $retrieved_time."
    [[ $1 == "-n" ]] && echo
fi

#-------------------------------------------------------------------------------
