#!/bin/bash
#===============================================================================
# A little bash script to make viewing information about the system easier :)
# Copyright (C) 2025-2026 kvastlund.
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#======> LIBRARIES <============================================================

. $(dirname "$(realpath "${BASH_SOURCE[0]}")")/utils.sh

#======> CONSTANTS <============================================================

readonly FETCHLINGS=(
                    "fastfetch --logo arch_old"
                    "hyfetch"
                    "macchina"
                    "screenfetch"
                    "archey"
                    "neofetch"
                    "ufetch"
                    "pfetch"
                    "alsi"
                    "catnap"
                    "zeptofetch"
                    "onefetch"
                    "uwufetch"
                    "footfetch"
                    "nitch"
                    "nitchrevived"
                    "zeitfetch"
                    "nanofetch"
                    "wretch"
                    "albafetch"
                    "aerofetch"
                    "ffetch"
                    "paleofetch"
                    "rxfetch"
                    "nerdfetch"
                    "brokefetch"
                    )

#======> FUNCTIONS <============================================================

_display_some_fetch() {
    # shellcheck disable=SC2068
    for fetchling in "${FETCHLINGS[@]}"; do
        if command -v ${fetchling%% *} >/dev/null 2>&1; then
            $fetchling
            return
        fi
    done

    # Backup info display
    echo "Kernel name:            $(uname -s)"
    echo "Network node hostname:  $(uname -n)"
    echo "Kernel release:         $(uname -r)"
    echo "Kernel version:         $(uname -v)"
    echo "Machine hardware name:  $(uname -m)"
    echo "Processor type:         $(uname -p)"
    echo "Hardware platform:      $(uname -i)"
    echo "Operating system:       $(uname -o)"
}

_display_the_rest() {
    paru -Ps

    echo -e "$(util_dateofbirth fancy)\n"
}

#======> DO THE THING! <========================================================

echo
util_truecolortest
echo
_display_some_fetch
echo
_display_the_rest
util_truecolortest
echo

#===============================================================================
