#!/bin/bash
#===============================================================================
# A little bash script to make updating and upgrading the system easier :)
# Copyright (C) 2024-2026 kvastlund
#
# This file is part of Janitor.
#
# Janitor is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Janitor is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Janitor. If not, see <https://www.gnu.org/licenses/>.
#===============================================================================

trap 'echo -e "\e[0m"; exit' INT

#======> LIBRARIES <============================================================

. $(dirname "$(realpath "${BASH_SOURCE[0]}")")/utils.sh

#======> CONSTANTS <============================================================

readonly TIMEOUT_DUR="10s"

SCRIPTS_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
readonly SCRIPTS_PATH

#======> NEWS! <================================================================

echo -e "\e[35m"
timeout $TIMEOUT_DUR paru -Pw
[[ $? -eq 124 ]] && echo "'paru -Pw' timed out after $TIMEOUT_DUR."
echo -ne "\e[0m"

#======> update official and AUR <==============================================

# Choose packages and dependencies
util_setup_pkgs ${@:1}

# Display mirrorlist retrieved time
util_mirtime pad

# Download and install
# shellcheck disable=SC2068
paru -Syu --sudoloop --upgrademenu --bottomup --cleanafter ${util_packages[@]}

# Set dependencies
util_set_deps

# Sort out the rest
sudo -E pacdiff
echo
"$SCRIPTS_PATH"/clean

#======> Goodbye <==============================================================

echo -e "\n\e[1;35mThank you for upgrading me! See you soon i hope :)\e[0m\n"
exit 0

#===============================================================================
