#!/bin/bash

#---------------------------------------------------------------------------------------------------------------------
# A little bash script to make unloading and reloading the wifi driver module easier :)
#---------------------------------------------------------------------------------------------------------------------

trap "echo; exit" INT

#---------------------------------------------------------------------------------------------------------------------

modulename=$(lspci -k | grep -zo "Network.*" | grep -am 1 "Kernel driver in use: " | rev | cut -d ' ' -f 1 | rev)

read -p "Try turning $modulename off and on again? [y/N] " -n 1 -r

[[ $REPLY != "" ]] && echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo modprobe -r $modulename
    sleep 1
    sudo modprobe $modulename
fi

#---------------------------------------------------------------------------------------------------------------------
